### ISSUE TITLE
Lambda/Alexa Skill Problem

### ISSUE THREAD

**Issue by gshafer** [bklavet/Alexa-ArduinoYun-garagedoor-skill#1]
Thanks for a great project. Exactly what I was looking for. 

I have gotten the Yun part to work fine. I can trigger the relay from a web browser.

I created the Alexa skill and Lambda function. When I test it I get an error:
"The remote endpoint could not be called, or the response it returned was invalid"

I can trigger the function from Alexa, and also get an error message that there was some issue with the response.

Seems like an issue with the Lambda code. Any ideas? I am not very familiar with Lambda on AWS.

Looks like Amazon has changed the interface a little since you documented it.

**Comment by bklavet** [comment]
hey gshafer,  
Yea, aws lambda did change things up abit.
make sure line 14 in the Index file is your arn from the alexa skill side, and that line 50 has your nearbus credentials.

also make sure you are creating a zip file that contains the Alexa and the index files and uploading them to aws lambda.  lambda will give you a function id that needs to go back to the alexa skill.

**Comment by gshafer** [comment]
I did manage to get the parts all connected and working. Some of it was just sloppy editing on my part and lack of knowledge on the Lambda and Alexa software. I didn't see a file in the download for the Sample Utterances. Finally figured out that the line "doorIntent blinds to {Control}" worked. Also when testing, had to use the word "tell" as in "tell blinds to open". 

Thanks again for the project. It was a great educational experience for me!

**Comment by bklavet** [comment]
I will dig up my sample utterance file and get it back on here. Sorry I missed it, but glad you sorted it out.
